### ISSUE TITLE
Cannot seem to output transparent background in YT-1

### ISSUE THREAD

**Issue by andrewminton** [hashlips-lab/hashlips-lab#1]
Having setup all layers, weighting and dragged a transparent png into the Background layer. I cannot seem to get my exporter to allow the background to remain transparent. There's a reason I need this which will be revealed in the collection, but for now struggling to find a way to allow final export to permit a transparency in the final image. 

Thoughts?

**Comment by liarco** [comment]
Hi @andrewminton, thank you for reporting this, I'm transferring the issue to the main repository.

You are right: the current implementation doesn't support tokens that end up with a completely transparent background. I'm gonna add this.

**Comment by andrewminton** [comment]
Awesome.  Is there a short work around here? I see the imageProssessor us defining a hex value in the setup of the final image using Background: 0x00000000 which denotes an Alpha background, but this doesn't seem to kick in. Is it due to the combine function reducing the final image to rgb? and therefore removing Alpha values in final comp? Wheras Blend does not.

**Comment by liarco** [comment]
Hi @andrewminton, thank you for your help!
I tested your solution and it worked fine, but I think I found a solution that works without additional packages:
https://github.com/hashlips-lab/hashlips-lab/blob/fb0e42fa3ef5785e9d1105d4826bdb258effbcb1/packages/art-engine/utils/processors/SharpImageProcessor.ts#L32

Would you mind try it out and see if it works on your side too? You can use a custom processor until we release a new `alpha` version of the package.

Thank you.

**Comment by andrewminton** [comment]
I can confirm it works like a charm.

**Comment by liarco** [comment]
Great! Thank you for time.
