### ISSUE TITLE
Duplicate DNA entry error after five or more data sets

### ISSUE THREAD

**Issue by Jharmony** [hashlips-lab/hashlips-lab#2]
After successfully being able to generate generative art with up to four different data sets, the generator seems to go on an endless loop, as shown here:
![image](https://user-images.githubusercontent.com/22645740/218913547-918ff3b7-8148-4bb9-a08e-f52e8fbef4c1.png)

Here is a screenshot of my index.js configuration file, which shows each data set correctly pointing to each generator:
![image](https://user-images.githubusercontent.com/22645740/218913490-22c8b1a5-1235-44d4-8ed9-2c9dba08b903.png)

Because of the scope of my collection, it would be beneficial to use a 5th and 6th data set for the correct collection generation. I appreciate any help you can provide.

**Comment by liarco** [comment]
Hi @Jharmony, I know we have been talking about this privately on the [Open Devs Crew](https://opendevs.io) Discord server, but I just wanna clarify here that having duplicate DNAs entries is not a problem, depending on your seed and the number of available traits you might be generating many duplicates, but the AE is gonna keep trying until it can generate fully unique values.

Thank you for your support!
