### ISSUE TITLE
After running AE one image out of the group is produce with extra properties

### ISSUE THREAD

**Issue by Jharmony** [hashlips-lab/hashlips-lab#3]
After each run of the AE, this included deleting both old output/cache folders. One image from the group is generated with different traits from another data set. This consists of the corresponding JSON file, which also shows different traits from other data sets. 

Here is an example from my collection: 
![956420247a7854f5e62073ee179314067a3342d8](https://user-images.githubusercontent.com/22645740/218924394-ef3bbc4f-dfbe-48a2-9850-d2a4678bb9ec.png)

And the corresponding JSON file:
![image](https://user-images.githubusercontent.com/22645740/218924370-8228cbab-55e1-441a-96eb-4a2731f533cf.png)

This issue can easily be solved by replacing the image and altering the JSON file, but I was hoping for a more programmatic fix. Thanks.

**Comment by liarco** [comment]
Hi @Jharmony, we have been talking about your collection on the [Open Devs Crew](https://opendevs.io) Discord server, but I wanna make sure this issue has been resolved, can you please confirm?

Thank you!

**Comment by Jharmony** [comment]
Hello @liarco. After the recent update to the AE 2.0, I can confirm that this error is no longer occurring. Thank you for all of your help over the past couple of weeks.
