### ISSUE TITLE
788 error path /Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas

### ISSUE THREAD

**Issue by cluck135** [hashlips-lab/hashlips-lab#9]
versions im running
node version: 16.0.0
npm version: 7.10.0

Currently running into this problem when i run: ```npm i @hashlips-lab/art-engine```

Something to do with the canvas element.

776 info run canvas@2.11.2 install { code: 1, signal: null }
777 timing reify:rollback:createSparse Completed in 80ms
778 timing reify:rollback:retireShallow Completed in 0ms
779 timing command:install Completed in 8005ms
780 verbose stack Error: command failed
780 verbose stack     at ChildProcess.<anonymous> (/Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
780 verbose stack     at ChildProcess.emit (node:events:365:28)
780 verbose stack     at maybeClose (node:internal/child_process:1067:16)
780 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
781 verbose pkgid canvas@2.11.2
782 verbose cwd /Users/casen/Desktop/Society-of-buddies/art-engine
783 verbose Darwin 21.6.0
784 verbose argv "/Users/casen/.nvm/versions/node/v16.0.0/bin/node" "/Users/casen/.nvm/versions/node/v16.0.0/bin/npm" "i" "@hashlips-lab/art-engine"
785 verbose node v16.0.0
786 verbose npm  v7.10.0
787 error code 1
788 error path /Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas
789 error command failed
790 error command sh -c node-pre-gyp install --fallback-to-build --update-binary
791 error Failed to execute '/Users/casen/.nvm/versions/node/v16.0.0/bin/node /Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
792 error node-pre-gyp info it worked if it ends with ok
792 error node-pre-gyp info using node-pre-gyp@1.0.10
792 error node-pre-gyp info using node@16.0.0 | darwin | arm64
792 error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-darwin-unknown-arm64.tar.gz
792 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-darwin-unknown-arm64.tar.gz
792 error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@16.0.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
792 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-darwin-unknown-arm64.tar.gz
792 error gyp info it worked if it ends with ok
792 error gyp info using node-gyp@7.1.2
792 error gyp info using node@16.0.0 | darwin | arm64
792 error gyp info ok
792 error gyp info it worked if it ends with ok
792 error gyp info using node-gyp@7.1.2
792 error gyp info using node@16.0.0 | darwin | arm64
792 error gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
792 error gyp http GET https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
792 error gyp http 200 https://nodejs.org/download/release/v16.0.0/node-v16.0.0-headers.tar.gz
792 error gyp http GET https://nodejs.org/download/release/v16.0.0/SHASUMS256.txt
792 error gyp http 200 https://nodejs.org/download/release/v16.0.0/SHASUMS256.txt
792 error (node:12691) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
792 error (Use `node --trace-deprecation ...` to show where the warning was created)
792 error gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
792 error gyp info spawn args [
792 error gyp info spawn args   '/Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
792 error gyp info spawn args   'binding.gyp',
792 error gyp info spawn args   '-f',
792 error gyp info spawn args   'make',
792 error gyp info spawn args   '-I',
792 error gyp info spawn args   '/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/config.gypi',
792 error gyp info spawn args   '-I',
792 error gyp info spawn args   '/Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
792 error gyp info spawn args   '-I',
792 error gyp info spawn args   '/Users/casen/Library/Caches/node-gyp/16.0.0/include/node/common.gypi',
792 error gyp info spawn args   '-Dlibrary=shared_library',
792 error gyp info spawn args   '-Dvisibility=default',
792 error gyp info spawn args   '-Dnode_root_dir=/Users/casen/Library/Caches/node-gyp/16.0.0',
792 error gyp info spawn args   '-Dnode_gyp_dir=/Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp',
792 error gyp info spawn args   '-Dnode_lib_file=/Users/casen/Library/Caches/node-gyp/16.0.0/<(target_arch)/node.lib',
792 error gyp info spawn args   '-Dmodule_root_dir=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas',
792 error gyp info spawn args   '-Dnode_engine=v8',
792 error gyp info spawn args   '--depth=.',
792 error gyp info spawn args   '--no-parallel',
792 error gyp info spawn args   '--generator-output',
792 error gyp info spawn args   'build',
792 error gyp info spawn args   '-Goutput_dir=.'
792 error gyp info spawn args ]
792 error /bin/sh: pkg-config: command not found
792 error gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
792 error gyp ERR! configure error
792 error gyp ERR! stack Error: `gyp` failed with exit code: 1
792 error gyp ERR! stack     at ChildProcess.onCpExit (/Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
792 error gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
792 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
792 error gyp ERR! System Darwin 21.6.0
792 error gyp ERR! command "/Users/casen/.nvm/versions/node/v16.0.0/bin/node" "/Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
792 error gyp ERR! cwd /Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas
792 error gyp ERR! node -v v16.0.0
792 error gyp ERR! node-gyp -v v7.1.2
792 error gyp ERR! not ok
792 error node-pre-gyp ERR! build error
792 error node-pre-gyp ERR! stack Error: Failed to execute '/Users/casen/.nvm/versions/node/v16.0.0/bin/node /Users/casen/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
792 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
792 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
792 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
792 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
792 error node-pre-gyp ERR! System Darwin 21.6.0
792 error node-pre-gyp ERR! command "/Users/casen/.nvm/versions/node/v16.0.0/bin/node" "/Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
792 error node-pre-gyp ERR! cwd /Users/casen/Desktop/Society-of-buddies/art-engine/node_modules/canvas
792 error node-pre-gyp ERR! node -v v16.0.0
792 error node-pre-gyp ERR! node-pre-gyp -v v1.0.10
792 error node-pre-gyp ERR! not ok
793 verbose exit 1

**Comment by liarco** [comment]
Hi @cluck135, it looks like your machine is not able to properly build dependencies. This is not directly related to our tool and we recently dropped canvas in favour of sharp which provides better compatibility and performance.

I hope this helps. I close this since canvas is not a dependency anymore.
